from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'ContractSentinel AI - Professional Audit Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by ContractSentinel', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(240, 240, 240)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()

def generate_pdf_report(analysis_json, filename):
    try:
        pdf = PDFReport()
        pdf.add_page()
        
        # --- 1. TITLE PAGE ---
        pdf.set_font("Arial", "B", 20)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 15, f"Contract Risk Assessment", ln=True, align='C')
        
        pdf.set_font("Arial", "", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Filename: {filename}", ln=True, align='C')
        
        score = analysis_json.get('risk_score', 0)
        risk_level = analysis_json.get('overall_risk_level', 'Unknown')
        
        pdf.ln(5)
        pdf.set_font("Arial", "B", 16)
        if score > 70: pdf.set_text_color(220, 53, 69)
        elif score > 40: pdf.set_text_color(255, 193, 7)
        else: pdf.set_text_color(40, 167, 69)
            
        pdf.cell(0, 10, f"Risk Score: {score}/100 ({risk_level})", ln=True, align='C')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)

        # --- 2. EXECUTIVE SUMMARY ---
        pdf.chapter_title("1. Executive Summary")
        pdf.chapter_body(analysis_json.get('summary', 'No summary provided.'))

        # --- 3. STRATEGIC ADVICE (New Section) ---
        pdf.chapter_title("2. Strategic Advice & Alternatives")
        advice = analysis_json.get('executive_advice', 'No specific advice generated.')
        pdf.set_font("Arial", "I", 11)
        pdf.multi_cell(0, 6, advice)
        pdf.ln(5)
        
        # --- 4. REDLINED RISK AREAS ---
        pdf.chapter_title("3. Redlined Risk Areas")
        clauses = analysis_json.get('clauses', [])
        high_risk = [c for c in clauses if c.get('risk_level') in ['High', 'Medium']]
        
        if not high_risk:
            pdf.cell(0, 10, "No critical risks found.", ln=True)
        
        for clause in high_risk:
            risk = clause.get('risk_level', 'Low')
            if risk == 'High':
                pdf.set_fill_color(255, 235, 238)
            else:
                pdf.set_fill_color(255, 243, 224)
                
            pdf.set_font("Arial", "B", 11)
            pdf.cell(0, 8, f" {clause.get('title')} ({risk})", ln=True, fill=False)
            
            pdf.set_font("Courier", "", 10)
            pdf.multi_cell(0, 6, f"\"{clause.get('original_text', '')}\"", border=1, fill=True)
            pdf.ln(2)
            
            pdf.set_font("Arial", "I", 10)
            pdf.multi_cell(0, 6, f"Fix: {clause.get('recommendation')}")
            pdf.ln(5)

        # --- CRITICAL: RETURN BYTES ---
        # This handles different FPDF versions safely
        try:
            return pdf.output(dest='S').encode('latin-1')
        except:
            return pdf.output()

    except Exception as e:
        # If PDF generation fails, return a basic error PDF byte string to prevent app crash
        print(f"PDF Error: {e}")
        return b"Error generating PDF"